### ISSUE TITLE
Todo List - 

### ISSUE THREAD

**Issue by pipewire-debian** [pipewire-debian/pipewire-debian#1]
# Todo
- [x]   Need to check #17
- [x]  Need to patch [this](https://gitlab.freedesktop.org/pipewire/pipewire/-/merge_requests/690), ~~IFF PipeWire upstream merge this MR~~ **Merged, need to check when 0.3.29 will be released** 
- [x]  Need to change the email id from `changelog` file under debian/
- [x]  libopenaptx0 dependency problem
- [x] ~~Solve libfdk-aac dependencies  on different ubuntu version~~ - Fixed, with compiling from source on every Ubuntu version
  - [x] Need to remove libfdk package from Launchpad repo. This is will be fixed in next version. 
- [x]  Handle all PW service (enabling,disabling) when ever install, remove or upgrade PW, Like Arch Linux. **Its already done before I forked.**
- [ ]  Improve Issue template 
- [x] Create a wiki that maintain a good documentaition how to make debian package.
  - [x] build depeendencies for only pipewire
  - [x] build dependencies for debian packaging
  - [x] inserting emoji to _Sidebar
  - [x] Include dependencies subsection _Sidebar
  - [x] build it locally `dpkg-buildpackage -b -rfakeroot [-uc,-us,-nc] [-k[GPG EMAIL]]`
    - [x] how to debianization a package, project/{project-version/{source-rootFiles,debian/},project_version.orig.tar.[xz,gz]}
	     - [x] what is debian/
	     - [x] what is debian/{changelog,control,rules,{pre,post}{inst,rm},*.install,patches/,.trigger,*shilib*,*maintscript*
  	  - [x] what is gpg signature, how it works for packagebuilding
          - [x] how to sign a package - `debsign`
     - [x] give source to build it launchpad itself `dput`,`debuild -S -s[a,d]`   
    - [x]  If a new Ver PW release, how to handle new files, deleted files, /debian/.symbols?
  - [x] build locally with meson prev and new version with custom buildir . create a local git repo. first move prev build dir to git repo && commit, 2nd mv new buildir to git repo && replace prev,don't commit or stage. just do a `git status && git status | grep deleted` and place them accordingly in your debian/*install files.
  - [x] If error occured for symbols, just `diff /debian/related-package.symbols and related-packages/DEBIAN/*symbol`  considering later version is correct, correct your debian/*symbol acording to later version.
  - [x] write your gpg short private key for signing without any option when building with `debuild` to ~/.devscripts in a variable `DEBSIGN_KEYID=${YOUR_KEY_ID}`
  - [x]  Troubleshooting Link in README should be added 
  - [x]  Include blueman wiki and Troubleshooting 
  - [x]  Include This repo Wiki page link in Readme
  - [x]  How to install build-dependencies from control file
  - [x]  Naming convension when build for multiple ubuntu versions "${PackName}-${Version}~ubuntu${version}" 
  - [ ]  Polish all wiki pages **WIP**
   

     

- [x]  All modification should done under @souravdas142.
  - [x]  blueman-git - latest git version of blueman is added Like a heading in readme
  - [x]  pipewire launchpad ppa description should know about this blueman-git
  - [x]  need to add blueman-git in our wiki pages and README.md , proper credits to original, wiki and troubleshoot etc
  - [x]  Need to add recent issue #4 in our troubleshoot page.

**Comment by jacksongoode** [comment]
Could you add clear installation instructions for Ubuntu from your PPA?

**Comment by pipewire-debian** [comment]
> Could you add clear installation instructions for Ubuntu from your PPA?

Updated README  1a5897c5e8525c0cc4e5339927597c6f2b8834a9 This github hosted [PPA](../#or-add-github-ppa) is not recommended for Normal *ubuntu distros, Add PPA from [launchpad](../#add-launchpad-ppa) then simply follow the rest of the [instruction](../#lets-follow-the-rest-of-installation-instruction-after-adding-one-of-the-above-two-ppa). Is it Clear to you now?
